#! /bin/sh

install ()
{
	d=$(pwd)
	echo 'install:' "${1}"
	cd "${1}" && pnpm i && cd "${d}"
}

install fixt/frontend
install fixt/frontend-typescript
install fixt/backend
install fixt/backend-typescript
install fixt/library
install fixt/library-typescript
